services:
  php_app:
    build:
      context: .
      dockerfile: docker/Dockerfile 
    container_name: php_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db_app
    networks:
      - app_network
    ports:
      - "${APP_PORT}:80"

  db_app:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - app_network
    volumes:
      - mysql_data:/var/lib/mysql
      - ./Config/my.cnf:/etc/mysql/my.cnf

  adminer:
    image: adminer
    container_name: adminer_ui
    restart: always
    ports:
      - "8081:8080"
    networks:
      - app_network

networks:
  app_network:

volumes:
  mysql_data: